export const AC_USER_LOGIN = 'USER_LOGIN';
export const AC_USER_LOGOUT = 'USER_LOGOUT';
export const AC_USER_INFO = 'USER_INFO';
export const AC_USER_RELOAD = 'USER_RELOAD';




export const AC_SHOP_LIST = 'SHOP_LIST';
export const AC_SHOP_INFO = 'SHOP_INFO';
export const AC_SHOP_MEMBER = 'SHOP_MEMBER';
export const AC_SHOP_PRODUCTS = 'SHOP_PRODUCTS';
export const AC_SHOP_FILL_CARD = 'SHOP_FILL_CARD';
export const AC_SHOP_ORDER_LIST = 'SHOP_ORDER_LIST';
export const AC_SHOP_CARD_LIST = 'SHOP_CARD_LIST';
export const AC_SHOP_CLEAR_CARD = 'SHOP_CLEAR_CARD';
export const AC_SHOP_CATEGORY_ID = 'SHOP_CATEGORY_ID';
export const AC_SHOP_CLEAR_PRODUCT = 'SHOP_CLEAR_PRODUCT';
export const AC_SHOP_SET_HEAD_ID = 'SHOP_SET_HEAD_ID';






export const AC_SHOP_ADD_TO_CARD = 'SHOP_ADD_TO_CARD';
export const AC_SHOP_REMOVE_FROM_CARD = 'SHOP_REMOVE_FROM_CARD';
